feature/events
MeqdamAlqudah/calculator-with-react pull request #3
Opened 2022-01-06 14:59 UTC by MeqdamAlqudah

1- Handle user events
2- add props to each element

2022-01-06 15:13 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hello 👋🏽  @MeqdamAlqudah 

Good job working on the project so far! 
✔️ You used state and props
✔️ There is no linter error
However, there are some issues that you need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- [ ] When I try to perform a calculation in your app, since the numbers are entered from the right hand side, it does not display correctly. For instance, in the image below, I want to do ``` 6 / 3 ``` but it is displayed as ``` 3 / 6 ```. Although the result is correct, I suggest you make the display correct for a better user experience.

<img width="417" alt="Screenshot 2022-01-06 at 16 07 38" src="https://user-images.githubusercontent.com/64774936/148404573-a0f3514c-44c3-4b13-a43e-f941c6dcf7bf.png">

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-01-06 15:13 UTC, Ghiftee commented on src/components/Calculator.js
> +// import calculate from './logic/calculate';
- [ ] Kindly remove commented code. This makes your codebase cleaner.

2022-01-06 15:13 UTC, Ghiftee commented on src/components/Calculator.js
> +    // };
- [ ] Kindly remove commented code. This makes your codebase cleaner.

2022-01-07 07:52 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @MeqdamAlqudah, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-07 08:48 UTC, merged